In [2]:
sys.path.append('/Users/liushuhan/Documents/AL_GNN/Experiments/RSP/Sythentic_graph')
sys.path.append('../')
from Generator import *
from util import *
from loss import *
from Estimator import *
from cluster import *
import matplotlib.pyplot as plt

In [27]:
group_label = [0]*5 + [1]*5
U, latent_features, node_features = sub_noisy_feature_generator(group_label, num_features=5, num_latent_features=3, standard_basis=False)

In [29]:
U

array([[-1.61573574,  0.71616355, -0.56957359],
       [-0.24513048, -0.67355546, -0.22860921],
       [ 1.48729034,  0.49428356, -0.41125193],
       [-1.21955879,  0.51802413, -1.01659806],
       [-0.3700487 , -1.03601812,  1.31336556]])

In [30]:
np.round(latent_features, 2)

array([[0.59, 0.72, 0.24, 0.17, 0.37, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.51, 0.47, 0.55, 0.56, 0.34],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.54, 0.29, 0.09, 0.87, 0.13]])

In [31]:
node_features

array([[-1.11615713, -1.44458914,  1.58988581, -1.89336386, -0.0671487 ],
       [ 0.35591224,  0.87503319,  3.68586397, -1.51066777,  0.98119564],
       [-0.93871655, -0.94685192,  0.77559307,  0.40459225, -1.88512368],
       [ 1.40099513, -0.93049335,  2.53071365, -0.03239337, -1.13403765],
       [ 0.40643746, -0.71758456,  1.48427009, -1.04733715, -1.80584896],
       [ 1.2871916 ,  0.41630526, -2.75307087, -1.08169027,  1.50056   ],
       [ 0.49031092,  0.07780657, -0.34083836, -0.2341491 ,  2.88490176],
       [ 1.01339137, -0.45600646,  0.77849233,  0.20665195,  0.58943399],
       [ 0.62037278, -0.40316732,  0.19584512, -1.44457231,  0.49609382],
       [ 1.67742976, -1.97241577, -0.89402891,  0.5421574 , -0.30597164]])